/**
 * AI Disclosure System — YouTube AI content disclosure compliance.
 *
 * Usage: node src/utils/disclosure.js <channel-id>
 * Output: data/research/<channel-id>/disclosure-spec.json
 *
 * YouTube's May 2026 update: if you don't disclose, they'll label it for you.
 * Labels can't be removed once applied. Best to self-disclose accurately.
 */

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, "..", "..");

/**
 * What requires disclosure vs what doesn't.
 */
const DISCLOSURE_RULES = {
  requires_disclosure: [
    {
      type: "Photorealistic AI visuals",
      description: "AI-generated scenes that could be mistaken for real footage",
      examples: ["Deepfake of a real person", "AI-generated news footage", "Fabricated real-world events"],
      risk: "HIGH",
    },
    {
      type: "Cloned voices of real people",
      description: "AI voice synthesis that mimics a specific identifiable person",
      examples: ["Celebrity voice clone", "Politician voice clone"],
      risk: "HIGH",
    },
    {
      type: "Altered footage of real events",
      description: "Digitally modified footage showing events that didn't happen",
      examples: ["Building fire that didn't occur", "Altered cityscape"],
      risk: "HIGH",
    },
  ],
  does_not_require_disclosure: [
    {
      type: "AI-generated scripts",
      description: "Scripts, outlines, or text generated by AI",
      notes: "Production assistance, not content generation",
    },
    {
      type: "AI thumbnails",
      description: "Thumbnail images created or enhanced by AI",
      notes: "Visual design, not realistic content",
    },
    {
      type: "AI voiceovers (non-impersonation)",
      description: "Text-to-speech that doesn't mimic a specific real person",
      notes: "Our EdgeTTS voices are generic neural voices, not clones",
    },
    {
      type: "AI color grading / enhancement",
      description: "Post-production AI tools for color, stabilization, upscaling",
      notes: "Minor aesthetic edits",
    },
    {
      type: "AI-assisted editing",
      description: "AI tools that help with cuts, transitions, effects",
      notes: "Production assistance",
    },
    {
      type: "Abstract / fantasy / animation",
      description: "Non-realistic content like animations, sci-fi scenes",
      notes: "Clearly not realistic — no reasonable viewer would be misled",
    },
    {
      type: "AI-generated data visualizations",
      description: "Charts, graphs, infographics created with AI assistance",
      notes: "Data presentation, not realistic content",
    },
  ],
};

/**
 * Determine disclosure requirements for our pipeline.
 */
function assessDisclosureNeeds(channel) {
  // Our pipeline uses:
  // - EdgeTTS (generic neural voices, NOT cloned) → NO disclosure needed
  // - AI-generated scripts → NO disclosure needed
  // - AI-assisted thumbnails → NO disclosure needed
  // - Stock B-roll from Pexels/Pixabay → NO disclosure needed
  // - Remotion rendering → NO disclosure needed
  // - AI color grading → NO disclosure needed

  const pipeline_components = [
    {
      component: "EdgeTTS voiceover",
      disclosure_required: false,
      reason: "Generic neural voice, not cloning a specific real person",
      policy: "Non-impersonation AI voices generally do not require disclosure",
    },
    {
      component: "AI-generated scripts",
      disclosure_required: false,
      reason: "Production assistance, not content generation",
      policy: "AI script generation does not require disclosure",
    },
    {
      component: "AI-assisted thumbnails",
      disclosure_required: false,
      reason: "Visual design, not realistic content",
      policy: "AI thumbnails do not require disclosure",
    },
    {
      component: "Stock B-roll footage",
      disclosure_required: false,
      reason: "Licensed stock footage from Pexels/Pixabay",
      policy: "Stock footage does not require disclosure",
    },
    {
      component: "Remotion video rendering",
      disclosure_required: false,
      reason: "Programmatic video assembly, not AI-generated realistic content",
      policy: "Video rendering tools do not require disclosure",
    },
  ];

  // Overall assessment
  const requiresAnyDisclosure = pipeline_components.some(
    (c) => c.disclosure_required
  );

  return {
    overall_disclosure_required: requiresAnyDisclosure,
    recommendation: requiresAnyDisclosure
      ? "Enable 'Altered or synthetic content' toggle during upload"
      : "Self-disclosure not required, but can enable if desired",
    pipeline_assessment: pipeline_components,
    auto_detection_note: "YouTube now auto-detects AI content. If you don't disclose, they'll label it for you. Labels can't be removed once applied.",
  };
}

/**
 * Generate upload checklist for disclosure compliance.
 */
function generateUploadChecklist(channel) {
  return {
    pre_upload: [
      "Review video content — does it contain photorealistic AI visuals?",
      "Check voiceover — does it clone a specific real person?",
      "Verify B-roll — is all footage from licensed sources?",
      "Assess overall — would a viewer be misled about authenticity?",
    ],
    upload_flow: {
      step_1: "Open YouTube Studio upload flow",
      step_2: "In the 'AI use' survey, select appropriate option",
      step_3: "If video contains realistic AI content → toggle 'Yes'",
      step_4: "If video does NOT contain realistic AI content → toggle 'No'",
      step_5: "Save and continue upload",
    },
    post_upload: [
      "Verify disclosure label appears correctly in video attributes",
      "Check that label is not incorrectly applied",
      "If mislabeled, update in YouTube Studio → Content → Attributes",
      "Monitor for any automated labels YouTube may add",
    ],
    our_position: {
      status: "Self-disclosure likely NOT required",
      reason: "Pipeline uses generic neural TTS (not cloned voices), AI scripts (production assistance), stock B-roll, and programmatic rendering — none of which trigger disclosure requirements",
      recommendation: "Select 'No' in AI use survey unless pipeline changes include photorealistic AI generation",
      risk: "YouTube auto-detection may still apply labels. Monitor and correct if needed.",
    },
  };
}

/**
 * Full disclosure spec generation.
 */
function generateDisclosureSpec(channel) {
  return {
    version: "1.0.0",
    generated_at: new Date().toISOString(),
    channel_id: channel.channel_id,
    channel_name: channel.channel_name,
    rules: DISCLOSURE_RULES,
    assessment: assessDisclosureNeeds(channel),
    upload_checklist: generateUploadChecklist(channel),
    policy_reference: {
      youtube_policy_url: "https://support.google.com/youtube/answer/14328491",
      effective_date: "March 2024 (enforcement began early 2025)",
      may_2026_update: "YouTube now auto-detects and labels AI content. Labels are permanent if content was made with YouTube's AI tools (Veo, Dream Screen) or contains C2PA metadata.",
      penalty_for_non_disclosure: "YouTube applies label automatically. Repeated failure may impact distribution. Disclosure alone does NOT impact monetization or recommendations.",
    },
    eu_ai_act: {
      effective_date: "August 2, 2026",
      requirement: "Any AI-generated content must be labeled unless human editorial review can be proven",
      notes: "Applies to EU audience. YouTube handles this through existing disclosure system.",
    },
  };
}

/**
 * CLI entry point.
 */
function main() {
  const channelId = process.argv[2];

  if (!channelId) {
    console.error("Usage: node disclosure.js <channel-id>");
    process.exit(1);
  }

  const channelsPath = join(ROOT, "config", "channels.json");
  const data = JSON.parse(readFileSync(channelsPath, "utf-8"));
  const channels = data.channels || data;
  const numId = parseInt(channelId, 10);
  const channel = channels.find((c) => c.id === numId || c.channel_id === channelId);
  if (!channel) {
    console.error(`Channel "${channelId}" not found`);
    process.exit(1);
  }

  const spec = generateDisclosureSpec(channel);

  const outDir = join(ROOT, "data", "research", channelId);
  mkdirSync(outDir, { recursive: true });

  const outPath = join(outDir, "disclosure-spec.json");
  writeFileSync(outPath, JSON.stringify(spec, null, 2));

  console.log(`Disclosure spec saved: ${outPath}`);
  console.log(`\nOverall disclosure required: ${spec.assessment.overall_disclosure_required}`);
  console.log(`Recommendation: ${spec.assessment.recommendation}`);
  console.log(`\nPipeline components:`);
  spec.assessment.pipeline_assessment.forEach((c) => {
    console.log(`  ${c.disclosure_required ? "⚠" : "✓"} ${c.component}: ${c.reason}`);
  });
}

export { generateDisclosureSpec, assessDisclosureNeeds, DISCLOSURE_RULES };

if (process.argv[1] && process.argv[1].endsWith("disclosure.js")) main();
