#!/usr/bin/env python3
"""Generates src/skills/remotion-render/visual/type-metrics.js: MEASURED advance
widths (em) of the two vendored families, so text fitting in canvas-layout.js
uses the glyphs actually drawn instead of per-character guesses.

  python3 scripts/gen-type-metrics.py        (needs: pip install fonttools brotli)

Fraunces is measured at opsz 144 (Chromium's font-optical-sizing: auto sets
opsz to the CSS px size, clamped to the axis max, so any headline / numeral
>= 144 px is exactly this; 88-144 px headlines run at a slightly larger opsz-
proportional width, covered by the 3% margin textWidth() adds). Kerning is
not applied here — real kerning only tightens, so a fit made on these
widths is safe, never tight.
"""
import json, os
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = os.path.join(os.path.dirname(__file__), "..")
FONTS = os.path.join(ROOT, "src", "skills", "remotion-render", "public", "fonts")
OUT = os.path.join(ROOT, "src", "skills", "remotion-render", "visual", "type-metrics.js")
CHARS = [chr(c) for c in range(32, 127)] + ["’", "‘", "“", "”", "–", "—", "…", "·", "é"]

def table(file, axes_list):
    out = {}
    for axes in axes_list:
        t = TTFont(os.path.join(FONTS, file))
        inst = instancer.instantiateVariableFont(t, axes)
        cmap, hm, upm = inst.getBestCmap(), inst["hmtx"], inst["head"].unitsPerEm
        out[str(axes["wght"])] = {ch: round(hm[cmap[ord(ch)]][0] / upm, 3) for ch in CHARS if ord(ch) in cmap}
        os2 = inst["OS/2"]
        out["capHeight"] = round(os2.sCapHeight / upm, 3)
        out["xHeight"] = round(os2.sxHeight / upm, 3)
    return out

data = {
    "fraunces": table("Fraunces-var.woff2", [{"wght": w, "opsz": 144} for w in (500, 600, 700)]),
    "inter": table("Inter-var.woff2", [{"wght": w} for w in (400, 500, 600, 700, 800)]),
}
with open(OUT, "w") as f:
    f.write("// GENERATED by scripts/gen-type-metrics.py from the vendored fonts — do not edit.\n"
            "// Advance widths in em, per weight; capHeight / xHeight in em.\n"
            "export const TYPE_METRICS = " + json.dumps(data, ensure_ascii=True, separators=(",", ":")) + ";\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes")
