// AUTO-GENERATED by fetch-fonts.js — do not edit.
import { staticFile } from "remotion";

/** All configured channel fonts as @font-face rules. */
export const FONT_FACES = `@font-face{font-family:"Space Grotesk";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/SpaceGrotesk-400.woff2")}") format("woff2");}
@font-face{font-family:"Space Grotesk";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/SpaceGrotesk-700.woff2")}") format("woff2");}
@font-face{font-family:"Inter";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/Inter-400.woff2")}") format("woff2");}
@font-face{font-family:"Inter";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/Inter-700.woff2")}") format("woff2");}
@font-face{font-family:"Playfair Display";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/PlayfairDisplay-400.woff2")}") format("woff2");}
@font-face{font-family:"Playfair Display";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/PlayfairDisplay-700.woff2")}") format("woff2");}
@font-face{font-family:"DM Sans";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/DMSans-400.woff2")}") format("woff2");}
@font-face{font-family:"DM Sans";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/DMSans-700.woff2")}") format("woff2");}
@font-face{font-family:"JetBrains Mono";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/JetBrainsMono-400.woff2")}") format("woff2");}
@font-face{font-family:"JetBrains Mono";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/JetBrainsMono-700.woff2")}") format("woff2");}
@font-face{font-family:"Oswald";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/Oswald-400.woff2")}") format("woff2");}
@font-face{font-family:"Oswald";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/Oswald-700.woff2")}") format("woff2");}
@font-face{font-family:"Nunito";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/Nunito-400.woff2")}") format("woff2");}
@font-face{font-family:"Nunito";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/Nunito-700.woff2")}") format("woff2");}
@font-face{font-family:"Lora";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/Lora-400.woff2")}") format("woff2");}
@font-face{font-family:"Lora";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/Lora-700.woff2")}") format("woff2");}
@font-face{font-family:"Cormorant Garamond";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/CormorantGaramond-400.woff2")}") format("woff2");}
@font-face{font-family:"Cormorant Garamond";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/CormorantGaramond-700.woff2")}") format("woff2");}
@font-face{font-family:"Roboto Condensed";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/RobotoCondensed-400.woff2")}") format("woff2");}
@font-face{font-family:"Roboto Condensed";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/RobotoCondensed-700.woff2")}") format("woff2");}
@font-face{font-family:"Crimson Pro";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/CrimsonPro-400.woff2")}") format("woff2");}
@font-face{font-family:"Crimson Pro";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/CrimsonPro-700.woff2")}") format("woff2");}
@font-face{font-family:"Source Serif 4";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/SourceSerif4-400.woff2")}") format("woff2");}
@font-face{font-family:"Source Serif 4";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/SourceSerif4-700.woff2")}") format("woff2");}
@font-face{font-family:"Barlow";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/Barlow-400.woff2")}") format("woff2");}
@font-face{font-family:"Barlow";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/Barlow-700.woff2")}") format("woff2");}
@font-face{font-family:"Nunito Sans";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/NunitoSans-400.woff2")}") format("woff2");}
@font-face{font-family:"Nunito Sans";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/NunitoSans-700.woff2")}") format("woff2");}
@font-face{font-family:"IBM Plex Sans";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/IBMPlexSans-400.woff2")}") format("woff2");}
@font-face{font-family:"IBM Plex Sans";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/IBMPlexSans-700.woff2")}") format("woff2");}
@font-face{font-family:"Barlow Condensed";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/BarlowCondensed-400.woff2")}") format("woff2");}
@font-face{font-family:"Barlow Condensed";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/BarlowCondensed-700.woff2")}") format("woff2");}
@font-face{font-family:"Archivo Black";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/ArchivoBlack-400.woff2")}") format("woff2");}
@font-face{font-family:"Source Sans 3";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/SourceSans3-400.woff2")}") format("woff2");}
@font-face{font-family:"Source Sans 3";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/SourceSans3-700.woff2")}") format("woff2");}
@font-face{font-family:"Plus Jakarta Sans";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/PlusJakartaSans-400.woff2")}") format("woff2");}
@font-face{font-family:"Plus Jakarta Sans";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/PlusJakartaSans-700.woff2")}") format("woff2");}
@font-face{font-family:"Bebas Neue";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/BebasNeue-400.woff2")}") format("woff2");}
@font-face{font-family:"Rubik";font-style:normal;font-weight:400;font-display:swap;src:url("${staticFile("fonts/Rubik-400.woff2")}") format("woff2");}
@font-face{font-family:"Rubik";font-style:normal;font-weight:700;font-display:swap;src:url("${staticFile("fonts/Rubik-700.woff2")}") format("woff2");}
`;

/** Family names of every font bundled above. */
export const FONT_FAMILIES = ["Space Grotesk","Inter","Playfair Display","DM Sans","JetBrains Mono","Oswald","Nunito","Lora","Cormorant Garamond","Roboto Condensed","Crimson Pro","Source Serif 4","Barlow","Nunito Sans","IBM Plex Sans","Barlow Condensed","Archivo Black","Source Sans 3","Plus Jakarta Sans","Bebas Neue","Rubik"];
